//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightNovelSniffer_CLI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LightNovelSniffer_CLI_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LightNovelSniffer_CLI_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightNovelSniffer_CLI.Resources.LightNovelSniffer-CLI_Strings", typeof(LightNovelSniffer_CLI_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add another version for this LN ?.
        /// </summary>
        internal static string AskAddAnotherLnVersion {
            get {
                return ResourceManager.GetString("AskAddAnotherLnVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover picture URL :.
        /// </summary>
        internal static string AskCoverUrl {
            get {
                return ResourceManager.GetString("AskCoverUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors (comma separated) :.
        /// </summary>
        internal static string AskCsvAuthor {
            get {
                return ResourceManager.GetString("AskCsvAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At which chapter do you want to start (if empty, 1) :.
        /// </summary>
        internal static string AskFirstChapterNumber {
            get {
                return ResourceManager.GetString("AskFirstChapterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At which chapter do you want to stop (if empty, until last parution) : .
        /// </summary>
        internal static string AskLastChapterNumber {
            get {
                return ResourceManager.GetString("AskLastChapterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LN name (empty to stop) :.
        /// </summary>
        internal static string AskLnName_EmptyToStop {
            get {
                return ResourceManager.GetString("AskLnName_EmptyToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No URL specified for {0} in this language. Please enter any chapter URL here :.
        /// </summary>
        internal static string AskLnUrl {
            get {
                return ResourceManager.GetString("AskLnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any chapter URL here :.
        /// </summary>
        internal static string AskLnVersionChapterUrl {
            get {
                return ResourceManager.GetString("AskLnVersionChapterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the language of this version (FR/EN/...) :.
        /// </summary>
        internal static string AskLnVersionLanguage {
            get {
                return ResourceManager.GetString("AskLnVersionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter the root folder path to use : .
        /// </summary>
        internal static string AskOutputFolder {
            get {
                return ResourceManager.GetString("AskOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use output folder &quot;{0}&quot; ?.
        /// </summary>
        internal static string AskOutputFolderConfirmation {
            get {
                return ResourceManager.GetString("AskOutputFolderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string AskQuestionChoicesNegativeAnswer {
            get {
                return ResourceManager.GetString("AskQuestionChoicesNegativeAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string AskQuestionChoicesPositiveAnswer {
            get {
                return ResourceManager.GetString("AskQuestionChoicesPositiveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to retrieve {0} ?.
        /// </summary>
        internal static string AskRetrieveLn {
            get {
                return ResourceManager.GetString("AskRetrieveLn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to retrieve the {0} version ?.
        /// </summary>
        internal static string AskRetrieveLnLanguage {
            get {
                return ResourceManager.GetString("AskRetrieveLnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of processing predefined LN. Do you want to process another ?.
        /// </summary>
        internal static string LogEndOfLnInConfig {
            get {
                return ResourceManager.GetString("LogEndOfLnInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No URL for the {0} version. Process stoped..
        /// </summary>
        internal static string LogNoLnUrlStopProcess {
            get {
                return ResourceManager.GetString("LogNoLnUrlStopProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No URL or language for this version. Unable to add it..
        /// </summary>
        internal static string LogNoUrlOrLanguageForThisVersion {
            get {
                return ResourceManager.GetString("LogNoUrlOrLanguageForThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of the program..
        /// </summary>
        internal static string LogProgramEnd {
            get {
                return ResourceManager.GetString("LogProgramEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning of the program..
        /// </summary>
        internal static string LogProgramStart {
            get {
                return ResourceManager.GetString("LogProgramStart", resourceCulture);
            }
        }
    }
}
